<?xml version="1.0" encoding="utf-8"?><Database Name="QL_OnThiTracNghiem1" Class="QLThiTracNghiemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ChiTietBaiThi" Member="ChiTietBaiThis">
    <Type Name="ChiTietBaiThi">
      <Column Name="MaBaiThi" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKQ" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CauTraLoi" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TrangThai" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="CauHoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KetQuaBaiThi_ChiTietBaiThi" Member="KetQuaBaiThi" ThisKey="MaKQ" OtherKey="MaKQ" Type="KetQuaBaiThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Chuong" Member="Chuongs">
    <Type Name="Chuong">
      <Column Name="MaChuong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChuong" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MaMonHoc" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Chuong_CauHoi" Member="CauHois" ThisKey="MaChuong" OtherKey="MaChuong" Type="CauHoi" />
      <Association Name="MonHoc_Chuong" Member="MonHoc" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDeThi" Member="ChiTietDeThis">
    <Type Name="ChiTietDeThi">
      <Column Name="MaChiTietDeThi" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaCauHoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDe" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="CauHoi_ChiTietDeThi" Member="CauHoi" ThisKey="MaCauHoi" OtherKey="MaCauHoi" Type="CauHoi" IsForeignKey="true" />
      <Association Name="DeThi_ChiTietDeThi" Member="DeThi" ThisKey="MaDe" OtherKey="MaDe" Type="DeThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CauHoi" Member="CauHois">
    <Type Name="CauHoi">
      <Column Name="MaCauHoi" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CauHoi" Member="CauHoi1" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DapAnA" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DapAnB" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DapAnC" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DapAnD" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DapAnDung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MucDo" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaMonHoc" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaChuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaGiaoVien" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CauHoi_ChiTietDeThi" Member="ChiTietDeThis" ThisKey="MaCauHoi" OtherKey="MaCauHoi" Type="ChiTietDeThi" />
      <Association Name="Chuong_CauHoi" Member="Chuong" ThisKey="MaChuong" OtherKey="MaChuong" Type="Chuong" IsForeignKey="true" />
      <Association Name="GiaoVien_CauHoi" Member="GiaoVien" ThisKey="MaGiaoVien" OtherKey="MaGiaoVien" Type="GiaoVien" IsForeignKey="true" />
      <Association Name="MonHoc_CauHoi" Member="MonHoc" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeThi" Member="DeThis">
    <Type Name="DeThi">
      <Column Name="MaDe" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaPhieuTaoDe" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MucDo" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DeThi_ChiTietDeThi" Member="ChiTietDeThis" ThisKey="MaDe" OtherKey="MaDe" Type="ChiTietDeThi" />
      <Association Name="DeThi_KetQuaBaiThi" Member="KetQuaBaiThis" ThisKey="MaDe" OtherKey="MaDe" Type="KetQuaBaiThi" />
      <Association Name="PhieuTaoDe_DeThi" Member="PhieuTaoDe" ThisKey="MaPhieuTaoDe" OtherKey="MaPhieuTaoDe" Type="PhieuTaoDe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiaoVien" Member="GiaoViens">
    <Type Name="GiaoVien">
      <Column Name="MaGiaoVien" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaMonHoc" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="GiaoVien_CauHoi" Member="CauHois" ThisKey="MaGiaoVien" OtherKey="MaGiaoVien" Type="CauHoi" />
      <Association Name="GiaoVien_PhieuTaoDe" Member="PhieuTaoDes" ThisKey="MaGiaoVien" OtherKey="MaGiaoVien" Type="PhieuTaoDe" />
      <Association Name="MonHoc_GiaoVien" Member="MonHoc" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HocSinh" Member="HocSinhs">
    <Type Name="HocSinh">
      <Column Name="Mssv" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CMND_CCCD" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Sdt" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="HocSinh_KetQuaBaiThi" Member="KetQuaBaiThis" ThisKey="Mssv" OtherKey="MaHS" Type="KetQuaBaiThi" />
      <Association Name="Lop_HocSinh" Member="Lop" ThisKey="MaLop" OtherKey="MaLop" Type="Lop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KetQuaBaiThi" Member="KetQuaBaiThis">
    <Type Name="KetQuaBaiThi">
      <Column Name="MaKQ" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Diem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaHS" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaDe" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="KetQuaBaiThi_ChiTietBaiThi" Member="ChiTietBaiThis" ThisKey="MaKQ" OtherKey="MaKQ" Type="ChiTietBaiThi" />
      <Association Name="DeThi_KetQuaBaiThi" Member="DeThi" ThisKey="MaDe" OtherKey="MaDe" Type="DeThi" IsForeignKey="true" />
      <Association Name="HocSinh_KetQuaBaiThi" Member="HocSinh" ThisKey="MaHS" OtherKey="Mssv" Type="HocSinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lop" Member="Lops">
    <Type Name="Lop">
      <Column Name="MaLop" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Lop_HocSinh" Member="HocSinhs" ThisKey="MaLop" OtherKey="MaLop" Type="HocSinh" />
    </Type>
  </Table>
  <Table Name="dbo.MonHoc" Member="MonHocs">
    <Type Name="MonHoc">
      <Column Name="MaMonHoc" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenMonHoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="MonHoc_Chuong" Member="Chuongs" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="Chuong" />
      <Association Name="MonHoc_CauHoi" Member="CauHois" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="CauHoi" />
      <Association Name="MonHoc_GiaoVien" Member="GiaoViens" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="GiaoVien" />
      <Association Name="MonHoc_PhieuTaoDe" Member="PhieuTaoDes" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="PhieuTaoDe" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuTaoDe" Member="PhieuTaoDes">
    <Type Name="PhieuTaoDe">
      <Column Name="MaPhieuTaoDe" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoLuongDe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoCauHoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianLamBai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaMonHoc" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaGiaoVien" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PhieuTaoDe_DeThi" Member="DeThis" ThisKey="MaPhieuTaoDe" OtherKey="MaPhieuTaoDe" Type="DeThi" />
      <Association Name="GiaoVien_PhieuTaoDe" Member="GiaoVien" ThisKey="MaGiaoVien" OtherKey="MaGiaoVien" Type="GiaoVien" IsForeignKey="true" />
      <Association Name="MonHoc_PhieuTaoDe" Member="MonHoc" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
</Database>